### ISSUE TITLE
Manage site: IndieAuth failure

### ISSUE THREAD

**Issue by Seirdy** [searchmysite/searchmysite.net#111]
I have a site, <https://seirdy.one/>, that I previously bought a full listing for. I wanted to renew this, so I attempted to log in with IndieAuth (the method I used previously). Upon successful completion of the PGP challenge on indielogin.com, I'm directed back to Search My Site with a 500 response code (internal server error).

1. ![Search My Site login page, with https://seirdy.one/ entered into the IndieAuth field.](https://seirdy.one/pb/1-login.png)
2. ![IndieAuth page with a "Continue" button labelled "Log in as https://seirdy.one/".](https://seirdy.one/pb/2-indieauth.png)
3. ![Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.](https://seirdy.one/pb/3-error.png)

**Comment by m-i-l** [comment]
The normal flow is that when a full listing expires, it becomes a free trial for 1 month, during which time you can still log in and resubscribe easily. After that free trial expires, it becomes a basic listing, and you can no longer log in. In that case, to resubscribe, you would resubmit your site as either a free trial or full listing, although you shouldn't need to reverify ownership of your site.

Now there is a known issue where if you have a basic listing but IndieAuth enabled on your site you can start to login but then get a not-very-helpful non-specific error - see #16  for details. I suspect that's what is happening here. If not, let me know, and I'll investigate further.

**Comment by m-i-l** [comment]
I think I have captured a log entry where this is happening:

```
[Mon Jan 22 08:42:30.322126 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582] [2024-01-22 08:42:30,321] INFO in auth: Got a success code from IndieAuth, referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335441 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582] [2024-01-22 08:42:30,332] ERROR in app: Exception on /login/ [GET], referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335513 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582] Traceback (most recent call last):, referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335518 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582]   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1455, in wsgi_app, referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335522 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582]     response = self.full_dispatch_request(), referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335525 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^, referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335528 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582]   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 869, in full_dispatch_request, referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335531 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582]     rv = self.handle_user_exception(e), referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335533 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^, referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335536 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582]   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 867, in full_dispatch_request, referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335539 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582]     rv = self.dispatch_request(), referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335541 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582]          ^^^^^^^^^^^^^^^^^^^^^^^, referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335544 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582]   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 852, in dispatch_request, referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335547 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args), referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335551 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^, referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335554 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582]   File "/usr/local/apache2/htdocs/dynamic/searchmysite/admin/auth.py", line 51, in login, referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335557 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582]     return_action, return_target = do_indieauth_login(current_page, next_page, addsite_workflow, insertdomainsql), referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335560 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582]                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^, referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335563 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582]   File "/usr/local/apache2/htdocs/dynamic/searchmysite/admin/auth.py", line 317, in do_indieauth_login, referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335566 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582]     if indexed_result is not None and indexed_result['owner_verified'] == True and indexed_result['contact_email'] is not None:, referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335569 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582]                                       ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^, referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335572 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582]   File "/usr/local/lib/python3.11/dist-packages/psycopg2/extras.py", line 171, in __getitem__, referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335575 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582]     x = self._index[x], referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335577 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582]         ~~~~~~~~~~~^^^, referer: https://indieauth.com/
[Mon Jan 22 08:42:30.335580 2024] [wsgi:error] [pid 9:tid 281473600712992] [client 172.18.0.1:44582] KeyError: 'owner_verified', referer: https://indieauth.com/
172.18.0.1 - - [22/Jan/2024:08:42:29 +0000] "GET /admin/login/?code=a657aa71cd2e5aa508d21c132ad90e75551f504e2e2e204931444d2c45733014&state=Gk7YkL5cIRdL HTTP/1.1" 500 265
```
This might be from the database changes made in release https://github.com/searchmysite/searchmysite.net/releases/tag/v1.1.0 . I've fixed the error and it is now possible to login with IndieAuth again, plus added more debugging to help with possible future IndieAuth issues. Closing for now.
