### ISSUE TITLE
Email sending has been broken by the email hosting migration

### ISSUE THREAD

**Issue by m-i-l** [searchmysite/searchmysite.net#162]
Server-side email sending, used e.g. on the Contact form at https://searchmysite.net/admin/contact/ , is broken. Given no emails have been sent or received in 5 weeks, this is presumably a result of the Email hosting migration (see https://github.com/searchmysite/searchmysite.net/issues/160 ) which was completed 5 weeks ago. Although the email migration was successfully tested shortly after completion, it is possible that it was tested too soon after with some caches still containing old details.

Error in the log when submitting the Contact form is:

```
ERROR in adminutils: Error sending email: Connection unexpectedly closed: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2546), referer: https://searchmysite.net/admin/contact/
...
File "/usr/local/apache2/htdocs/dynamic/searchmysite/adminutils.py", line 154, in send_email, referer: https://searchmysite.net/admin/contact/
     server.quit(), referer: https://searchmysite.net/admin/contact/
...
smtplib.SMTPServerDisconnected: please run connect() first, referer: https://searchmysite.net/admin/contact/
```

**Comment by m-i-l** [comment]
Updated values for SMTP_SERVER and SMTP_PORT and now see the following error:

```
Traceback (most recent call last):, referer: https://searchmysite.net/admin/contact/
   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1473, in wsgi_app, referer: https://searchmysite.net/admin/contact/
...
   File "/usr/local/apache2/htdocs/dynamic/searchmysite/adminutils.py", line 154, in send_email, referer: https://searchmysite.net/admin/contact/
     server.quit(), referer: https://searchmysite.net/admin/contact/
    ^^^^^^, referer: https://searchmysite.net/admin/contact/
UnboundLocalError: cannot access local variable 'server' where it is not associated with a value, referer: https://searchmysite.net/admin/contact/
```

**Comment by m-i-l** [comment]
Updated code (changing smtplib.SMTP to smtplib.SMTP_SSL) works on dev, but not on prod. Seems to timeout on `server = smtplib.SMTP_SSL(host=smtp_server, port=smtp_port, context=context)` so I can't get more debug info. Raising a ticket with the email hosting provider.

**Comment by m-i-l** [comment]
As per https://docs.hetzner.com/cloud/servers/faq/#why-can-i-not-send-any-mails-from-my-server , Hetzner blocks port 465 but not 587 (but doesn't show this on the console, which in my case says all outgoing ports are enabled), so you need to raised a request to get 465 enabled. I've done so, and it is working now.
